### ISSUE TITLE
Please update your documentation, there seems to be a bit of an error when installing the software

### ISSUE THREAD

**Issue by MaiyonDevWindows** [cd-athena/DoFP-Plus#1]
`Bug description:`
- Firstly, I installed Gurobi version 10, I can add it to Ubuntu and then I have to install python3.9-distutils to run it:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/053f0537-8823-4c5e-81ba-320638ca01cd)
- I also installed libraries like cmake, go, zlib, libevent in the latest version.
- Next I installed boringssl but the specific version in readme.md couldn't build so I had to use the latest version:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/5265848f-1f2b-43c7-ab70-55503fd0ce10)
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/6f54fd7a-65cd-4177-af0a-f5e88025ea14)
- This is boringssl when installing the latest and successful, then I will install lsquic like readme.md:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/d56957ff-00c1-48d5-a575-f8b71121c951)
- Here, My_updates is a fork of dofp, but readme.md mentions installing lsquic, however, my_updates of dofp I build also fails, so I just install lsquic:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/d85e700a-b83a-4a1c-af10-aecd361b2af4)
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/2a463bf8-1b9e-4f27-babf-b88ae4057685)
- Installing lsquic is also simple, static or dynamic are successful:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/f0492963-9e03-49db-8303-4a0bb507ff25)
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/681f7c51-27ce-4eed-9cfd-61859121c2ae)
- However when I build dofp+ it gives the following error:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/a6196bcb-f0c8-4e2c-bd6e-faa4632831e7)
- Then I think it's because dofp+ doesn't have submodules like dofp or lsquic so the file is missing, then I can add the missing files by copying the file from lsquic built from the previous step into dofp+/src, then rebuild the error as follows:
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/68bac593-a38e-4713-a43c-a50f7a729ecd)
![image](https://github.com/cd-athena/DoFP-Plus/assets/79782970/3c9376d7-201f-4436-9362-c73b3e94ba67)

How should it be installed and working in your opinion?

`Information of computer installed software`

- Ubuntu 64-bit GUI on VmWare, Windows 11 64-bit.
- B660M Pro RS, Intel Core i5-13500, 32gb Ram, Radeon RX 580.
- [DoFP+ Version](https://github.com/cd-athena/DoFP-Plus)

**Comment by minhkstn** [comment]
Thank you for your feedback. We are working on it to fix this issue.

**Comment by minhkstn** [comment]
Hello @MaiyonDevWindows ,

I have updated the README.md file. Would you please try it again from scratch?

**Comment by MaiyonDevWindows** [comment]
I will try and reply back to you soon, many thanks to you.

**Comment by minhkstn** [comment]
This issue has been inactive for a long time, so I'm closing it. If you're still experiencing this issue, please feel free to reopen it and provide any additional information that may be helpful.
