### ISSUE TITLE
python3: can't open file 'compute-metrics.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by NullLimite** [cd-athena/DoFP-Plus#2]
![image](https://github.com/cd-athena/DoFP-Plus/assets/20982456/fb65b824-f2bf-4d44-b0a1-a02e91123fc0)

**Comment by minhkstn** [comment]
@zenzi-deluxe can you support this issue? Thanks!

**Comment by zenzi-deluxe** [comment]
Hi @NullLimite, I just realized that the upload of `compute-metrics.py` has not succeeded. I re-uploaded it in the main folder. 
Just download it and place it in the root directory. It should work now.

**Comment by NullLimite** [comment]
Ok, I have seen it. Thanks!
